version: "3"
services:
  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb
  sensor:
    image: sensor
    build: 
      context: "."
      dockerfile: sensor/Dockerfile
    links:
      - influxdb
  control:
    image: control
    build:
      context: "."
      dockerfile: control/Dockerfile
    links:
      - influxdb

  #test:
  #  image: test
  #  build: 
  #    context: "."
  #    dockerfile: test/Dockerfile
  #  links:
  #    - influxdb
  #arima:
  #  image: arima
  #  build: 
  #    context: "."
  #    dockerfile: arima/Dockerfile
  #  links:
  #    - influxdb
      
  peaks:
    image: peaks
    build: 
      context: "."
      dockerfile: peaks/Dockerfile
    volumes:
      - ./settings.json:/mnt/c/Users/grunw/Desktop/BP/dockerized/settings.json

  #  links:
  #    - influxdb
      
  dashboard:
    image: grafana/grafana
    links:
      - sensor
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana

volumes:
  influxdb:
  grafana:
